version: '3.8'
services:
  vault:
    image: vault:1.8.5
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: 'http://127.0.0.1:8200'
      VAULT_TOKEN: myroot
    container_name: vault
    ports:
      - 8200:8200
    # volumes:
    #   - ./volumes/config:/vault/config
    cap_add:
      - IPC_LOCK
    # entrypoint: ["vault"]
